### ISSUE TITLE
Recommendations for alternatives?

### ISSUE THREAD

**Issue by NiKiZe** [kittennbfive/free-373#1]
There is suggestions that this is an old device that no-one uses anymore?
If so what is everyone using these days instead? V3.0? (Just got one 2.0 cheap, might be getting more so have an interest if I can use them to stream to PC with audio)

**Comment by kittennbfive** [comment]
Hi,

yes, the 373 without A is an old device as far as i know, it has been replaced by the 373*A*. However if you want to stream directly to a PC over a short distance i would recommend using a HDMI-USB adapter directly. They are cheap and work fine under Linux (at least the one i have, bought on Aliexpress some time ago).
